development:
  adapter: postgresql
  database: eventplanner_development
  username: eventplanner
  password: asdf;lkj

test: &test
  adapter: postgresql
  database: eventplanner_test
  username: eventplanner
  password: asdf;lkj

production:
  adapter: postgresql
  database: eventplanner_production
  username: eventplanner
  password: asdf;lkj
cucumber:
  <<: *test